# Name of your application. Used to uniquely configure containers.
service: ministry_of_homeland_security

# Name of the container image.
image: idclofficial/ministry_of_homeland_security

# Deploy to these servers.
servers:
  web:
    - 15.237.252.202

proxy:
  ssl: true
  host: homesecurity.im.gov.ng
  app_port: 3000
  healthcheck:
    path: /

# Credentials for your image host.
registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

ssh:
  user: ubuntu

# Configure builder setup.
builder:
  arch: amd64
  cache:
    type: gha
  secrets:
    - KAMAL_REGISTRY_USERNAME
    - KAMAL_REGISTRY_PASSWORD
  args:
    NEXT_PUBLIC_MINISTRY_ID: <% ENV["NEXT_PUBLIC_MINISTRY_ID"] %>
    NEXT_PUBLIC_CONTENTFUL_SPACE_ID: <% ENV["NEXT_PUBLIC_CONTENTFUL_SPACE_ID"] %>
    NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN: <% ENV["NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN"] %>
    NEXT_PUBLIC_CONTENTFUL_PREVIEW_ACCESS_TOKEN: <% ENV["NEXT_PUBLIC_CONTENTFUL_PREVIEW_ACCESS_TOKEN"] %>
    NEXT_PUBLIC_ADMIN_SALT: <% ENV["NEXT_PUBLIC_ADMIN_SALT"] %>
    NEXT_PUBLIC_ADMIN_EMAIL: <% ENV["NEXT_PUBLIC_ADMIN_EMAIL"] %>
    NEXT_PUBLIC_ADMIN_PASSWORD: <% ENV["NEXT_PUBLIC_ADMIN_PASSWORD"] %>
    OPENAI_API_KEY: <% ENV["OPENAI_API_KEY"] %>
    RESEND_API_KEY: <% ENV["RESEND_API_KEY"] %>
env:
  clear:
    NEXTAUTH_URL: https://homesecurity.im.gov.ng
  secret:
    - ADMIN_EMAIL
    - NEXTAUTH_SECRET
    - OPENAI_API_KEY
    - RESEND_API_KEY
